/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.stock;
        import com.today.api.purchase.request.serializer.*;import com.today.api.common.serializer.*;import com.today.api.purchase.response.serializer.*;import com.today.api.stock.response.serializer.*;import com.today.api.stock.request.serializer.*;import com.today.api.stock.events.serializer.*;import com.today.api.stock.vo.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import com.github.dapeng.core.definition.SoaServiceDefinition;
        import com.github.dapeng.core.definition.SoaFunctionDefinition;

        import java.io.BufferedReader;
        import java.io.InputStreamReader;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;
        import com.today.api.stock.StockServiceSuperCodec.*;

        import com.today.api.stock.service.StockServiceAsync;
        /**
        * Autogenerated by Dapeng-Code-Generator (2.1.1)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class StockServiceAsyncCodec {

        

            public static class addStockAction<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, addStockAction_args, addStockAction_result>
            {
              public addStockAction()
              {
                super("addStockAction", new AddStockAction_argsSerializer(),  new AddStockAction_resultSerializer());
              }

              @Override
              public CompletableFuture<addStockAction_result> apply(StockServiceAsync iface, addStockAction_args addStockAction_args) throws SoaException
              {
                CompletableFuture<Void> result = (CompletableFuture<Void>) iface.addStockAction(addStockAction_args.getRequest());
                return result.thenApply((Void) -> {
                  addStockAction_result res = new addStockAction_result();
                  
                  return res;
              });
              }

            }
          

            public static class updateInventoryAction<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, updateInventoryAction_args, updateInventoryAction_result>
            {
              public updateInventoryAction()
              {
                super("updateInventoryAction", new UpdateInventoryAction_argsSerializer(),  new UpdateInventoryAction_resultSerializer());
              }

              @Override
              public CompletableFuture<updateInventoryAction_result> apply(StockServiceAsync iface, updateInventoryAction_args updateInventoryAction_args) throws SoaException
              {
                CompletableFuture<Void> result = (CompletableFuture<Void>) iface.updateInventoryAction(updateInventoryAction_args.getRequest());
                return result.thenApply((Void) -> {
                  updateInventoryAction_result res = new updateInventoryAction_result();
                  
                  return res;
              });
              }

            }
          

            public static class deleteStock<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, deleteStock_args, deleteStock_result>
            {
              public deleteStock()
              {
                super("deleteStock", new DeleteStock_argsSerializer(),  new DeleteStock_resultSerializer());
              }

              @Override
              public CompletableFuture<deleteStock_result> apply(StockServiceAsync iface, deleteStock_args deleteStock_args) throws SoaException
              {
                CompletableFuture<Void> result = (CompletableFuture<Void>) iface.deleteStock(deleteStock_args.getIds());
                return result.thenApply((Void) -> {
                  deleteStock_result res = new deleteStock_result();
                  
                  return res;
              });
              }

            }
          

            public static class getStockByOwnerId<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, getStockByOwnerId_args, getStockByOwnerId_result>
            {
              public getStockByOwnerId()
              {
                super("getStockByOwnerId", new GetStockByOwnerId_argsSerializer(),  new GetStockByOwnerId_resultSerializer());
              }

              @Override
              public CompletableFuture<getStockByOwnerId_result> apply(StockServiceAsync iface, getStockByOwnerId_args getStockByOwnerId_args) throws SoaException
              {
                CompletableFuture<com.today.api.purchase.response.StockQueryResponse> result = (CompletableFuture<com.today.api.purchase.response.StockQueryResponse>) iface.getStockByOwnerId(getStockByOwnerId_args.getStockQueryRequest());
                return result.thenApply(( com.today.api.purchase.response.StockQueryResponse i) -> {
                  getStockByOwnerId_result res = new getStockByOwnerId_result();
                  res.setSuccess(i);
                  return res;
              });
              }

            }
          

            public static class listSkuStockByStoreCode<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, listSkuStockByStoreCode_args, listSkuStockByStoreCode_result>
            {
              public listSkuStockByStoreCode()
              {
                super("listSkuStockByStoreCode", new ListSkuStockByStoreCode_argsSerializer(),  new ListSkuStockByStoreCode_resultSerializer());
              }

              @Override
              public CompletableFuture<listSkuStockByStoreCode_result> apply(StockServiceAsync iface, listSkuStockByStoreCode_args listSkuStockByStoreCode_args) throws SoaException
              {
                CompletableFuture<com.today.api.purchase.response.ListSkuStockByStoreCodeResponse> result = (CompletableFuture<com.today.api.purchase.response.ListSkuStockByStoreCodeResponse>) iface.listSkuStockByStoreCode(listSkuStockByStoreCode_args.getRequest());
                return result.thenApply(( com.today.api.purchase.response.ListSkuStockByStoreCodeResponse i) -> {
                  listSkuStockByStoreCode_result res = new listSkuStockByStoreCode_result();
                  res.setSuccess(i);
                  return res;
              });
              }

            }
          

            public static class listStockByStoreId<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, listStockByStoreId_args, listStockByStoreId_result>
            {
              public listStockByStoreId()
              {
                super("listStockByStoreId", new ListStockByStoreId_argsSerializer(),  new ListStockByStoreId_resultSerializer());
              }

              @Override
              public CompletableFuture<listStockByStoreId_result> apply(StockServiceAsync iface, listStockByStoreId_args listStockByStoreId_args) throws SoaException
              {
                CompletableFuture<com.today.api.purchase.response.ListStockByStoreIdResponse> result = (CompletableFuture<com.today.api.purchase.response.ListStockByStoreIdResponse>) iface.listStockByStoreId(listStockByStoreId_args.getRequest());
                return result.thenApply(( com.today.api.purchase.response.ListStockByStoreIdResponse i) -> {
                  listStockByStoreId_result res = new listStockByStoreId_result();
                  res.setSuccess(i);
                  return res;
              });
              }

            }
          

            public static class listInventoryTransOutInfo<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, listInventoryTransOutInfo_args, listInventoryTransOutInfo_result>
            {
              public listInventoryTransOutInfo()
              {
                super("listInventoryTransOutInfo", new ListInventoryTransOutInfo_argsSerializer(),  new ListInventoryTransOutInfo_resultSerializer());
              }

              @Override
              public CompletableFuture<listInventoryTransOutInfo_result> apply(StockServiceAsync iface, listInventoryTransOutInfo_args listInventoryTransOutInfo_args) throws SoaException
              {
                CompletableFuture<com.today.api.purchase.response.InventoryTransOutQueryResponse> result = (CompletableFuture<com.today.api.purchase.response.InventoryTransOutQueryResponse>) iface.listInventoryTransOutInfo(listInventoryTransOutInfo_args.getRequest());
                return result.thenApply(( com.today.api.purchase.response.InventoryTransOutQueryResponse i) -> {
                  listInventoryTransOutInfo_result res = new listInventoryTransOutInfo_result();
                  res.setSuccess(i);
                  return res;
              });
              }

            }
          

            public static class updateStockByStoreAndSkuNos<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, updateStockByStoreAndSkuNos_args, updateStockByStoreAndSkuNos_result>
            {
              public updateStockByStoreAndSkuNos()
              {
                super("updateStockByStoreAndSkuNos", new UpdateStockByStoreAndSkuNos_argsSerializer(),  new UpdateStockByStoreAndSkuNos_resultSerializer());
              }

              @Override
              public CompletableFuture<updateStockByStoreAndSkuNos_result> apply(StockServiceAsync iface, updateStockByStoreAndSkuNos_args updateStockByStoreAndSkuNos_args) throws SoaException
              {
                CompletableFuture<Void> result = (CompletableFuture<Void>) iface.updateStockByStoreAndSkuNos(updateStockByStoreAndSkuNos_args.getStoreId(),updateStockByStoreAndSkuNos_args.getSkuNoList());
                return result.thenApply((Void) -> {
                  updateStockByStoreAndSkuNos_result res = new updateStockByStoreAndSkuNos_result();
                  
                  return res;
              });
              }

            }
          

            public static class calculateElemStock<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, calculateElemStock_args, calculateElemStock_result>
            {
              public calculateElemStock()
              {
                super("calculateElemStock", new CalculateElemStock_argsSerializer(),  new CalculateElemStock_resultSerializer());
              }

              @Override
              public CompletableFuture<calculateElemStock_result> apply(StockServiceAsync iface, calculateElemStock_args calculateElemStock_args) throws SoaException
              {
                CompletableFuture<Void> result = (CompletableFuture<Void>) iface.calculateElemStock();
                return result.thenApply((Void) -> {
                  calculateElemStock_result res = new calculateElemStock_result();
                  
                  return res;
              });
              }

            }
          

        public static class getServiceMetadata<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, getServiceMetadata_args, getServiceMetadata_result> {
          public getServiceMetadata() {
            super("getServiceMetadata", new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer());
          }

          @Override
          public CompletableFuture<getServiceMetadata_result> apply(I iface, getServiceMetadata_args args) {
            getServiceMetadata_result result = new getServiceMetadata_result();

            //fake async method, to avoid using the JDK default ForkJoinPool.common, which will case heap-off OOM
            CompletableFuture<getServiceMetadata_result> resultFuture = new CompletableFuture<>();

            try (InputStreamReader isr = new InputStreamReader(StockServiceCodec.class.getClassLoader().getResourceAsStream("com.today.api.stock.service.StockService.xml"));
            BufferedReader in = new BufferedReader(isr)) {
              int len = 0;
              StringBuilder str = new StringBuilder("");
              String line;
              while ((line = in.readLine()) != null) {

                if (len != 0) {
                  str.append("\r\n").append(line);
                } else {
                  str.append(line);
                }
                len++;
              }
              result.setSuccess(str.toString());
            } catch (Exception e) {
              e.printStackTrace();
              result.setSuccess("");
            }
            resultFuture.complete(result);
            return resultFuture;
          }

        }

        public static class echo<I extends StockServiceAsync> extends SoaFunctionDefinition.Async<I, echo_args, echo_result> {
          public echo() {
            super("echo", new echo_argsSerializer(), new echo_resultSerializer());
          }

          @Override
          public CompletableFuture<echo_result> apply(I iface, echo_args args) {
            echo_result result = new echo_result();
            CompletableFuture<echo_result> resultFuture = new CompletableFuture<>();

            String echoMsg = (String) TransactionContext.Factory.currentInstance().getAttribute("container-threadPool-info");
            result.setSuccess(echoMsg);
            //result.setSuccess("PONG");
            resultFuture.complete(result);
            return resultFuture;
          }

        }




        @SuppressWarnings("unchecked")
        public static class Processor<I extends StockServiceAsync> extends SoaServiceDefinition<StockServiceAsync>
        {

          public Processor(StockServiceAsync iface, Class<StockServiceAsync> ifaceClass)
          {
            super(iface, ifaceClass, buildMap(new java.util.HashMap<>()));
          }

          @SuppressWarnings("unchecked")
          private static <I extends StockServiceAsync> java.util.Map<String, SoaFunctionDefinition<I, ?, ?>> buildMap(java.util.Map<String, SoaFunctionDefinition<I, ?, ?>> processMap)
          {
            
                processMap.put("addStockAction", new addStockAction());
              
                processMap.put("updateInventoryAction", new updateInventoryAction());
              
                processMap.put("deleteStock", new deleteStock());
              
                processMap.put("getStockByOwnerId", new getStockByOwnerId());
              
                processMap.put("listSkuStockByStoreCode", new listSkuStockByStoreCode());
              
                processMap.put("listStockByStoreId", new listStockByStoreId());
              
                processMap.put("listInventoryTransOutInfo", new listInventoryTransOutInfo());
              
                processMap.put("updateStockByStoreAndSkuNos", new updateStockByStoreAndSkuNos());
              
                processMap.put("calculateElemStock", new calculateElemStock());
              
            processMap.put("getServiceMetadata", new getServiceMetadata());
            processMap.put("echo", new echo());
            return processMap;
          }
        }

      }
      