package com.isuwang.soa.user.scala

        import com.github.dapeng.core._;
        import com.github.dapeng.org.apache.thrift._;
        import java.util.ServiceLoader;
        import java.util.concurrent.CompletableFuture;
        import com.isuwang.soa.user.scala.UserServiceAsyncCodec._;
        import com.isuwang.soa.user.scala.service.UserServiceAsync;
        import scala.compat.java8.FutureConverters._
        import scala.concurrent.duration._
        import scala.concurrent.Future
        import scala.concurrent.ExecutionContext.Implicits.global

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        class UserServiceAsyncClient extends UserServiceAsync {

        val serviceName = "com.isuwang.soa.user.service.UserService"
        val version = "1.0.0"
        val pool = {
          val serviceLoader = ServiceLoader.load(classOf[SoaConnectionPoolFactory])
          if (serviceLoader.iterator().hasNext) {
            val poolImpl = serviceLoader.iterator().next().getPool
            poolImpl.registerClientInfo(serviceName,version)
            poolImpl
          } else null
        }

        def getServiceMetadata: String = {
          pool.send(
          serviceName,
          version,
          "getServiceMetadata",
          new getServiceMetadata_args,
          new GetServiceMetadata_argsSerializer,
          new GetServiceMetadata_resultSerializer
          ).success
        }


        

            /**
            * 
            **/
            def createUser(user:com.isuwang.soa.user.scala.domain.User 
            , timeout: Long = 5000) : Future[Unit] = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "createUser",
            createUser_args(user),
            new CreateUser_argsSerializer(),
            new CreateUser_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[createUser_result]]

            toScala(response).map(null)

          }

          

            /**
            * 
            **/
            def getUserById(userId:Int 
            , timeout: Long = 5000) : Future[com.isuwang.soa.user.scala.domain.User] = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "getUserById",
            getUserById_args(userId),
            new GetUserById_argsSerializer(),
            new GetUserById_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[getUserById_result]]

            toScala(response).map(_.success)

          }

          
      }
      