/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.stock.request;

        import java.util.Optional;
        import com.github.dapeng.org.apache.thrift.TException;
        import com.github.dapeng.org.apache.thrift.protocol.TCompactProtocol;
        import com.github.dapeng.util.TCommonTransport;

        /**
         * Autogenerated by Dapeng-Code-Generator (2.2.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

        *
        **/
        public class AddStockByAppReturnRequest{
        
            /**
            *

 门店财务 ID

            **/
            public String storeId ;
            public String getStoreId(){ return this.storeId; }
            public void setStoreId(String storeId){ this.storeId = storeId; }

            public String storeId(){ return this.storeId; }
            public AddStockByAppReturnRequest storeId(String storeId){ this.storeId = storeId; return this; }
          
            /**
            *

 库存扣减项集合

            **/
            public java.util.List<com.today.api.stock.request.AddStockByAppReturnRequestItem> deductStockItem = new java.util.ArrayList();
            public java.util.List<com.today.api.stock.request.AddStockByAppReturnRequestItem> getDeductStockItem(){ return this.deductStockItem; }
            public void setDeductStockItem(java.util.List<com.today.api.stock.request.AddStockByAppReturnRequestItem> deductStockItem){ this.deductStockItem = deductStockItem; }

            public java.util.List<com.today.api.stock.request.AddStockByAppReturnRequestItem> deductStockItem(){ return this.deductStockItem; }
            public AddStockByAppReturnRequest deductStockItem(java.util.List<com.today.api.stock.request.AddStockByAppReturnRequestItem> deductStockItem){ this.deductStockItem = deductStockItem; return this; }
          

        public static byte[] getBytesFromBean(AddStockByAppReturnRequest bean) throws TException {
          byte[] bytes = new byte[]{};
          TCommonTransport transport = new TCommonTransport(bytes, TCommonTransport.Type.Write);
          TCompactProtocol protocol = new TCompactProtocol(transport);

          new com.today.api.stock.request.serializer.AddStockByAppReturnRequestSerializer().write(bean, protocol);
          transport.flush();
          return transport.getByteBuf();
        }

        public static AddStockByAppReturnRequest getBeanFromBytes(byte[] bytes) throws TException {
          TCommonTransport transport = new TCommonTransport(bytes, TCommonTransport.Type.Read);
          TCompactProtocol protocol = new TCompactProtocol(transport);
          return new com.today.api.stock.request.serializer.AddStockByAppReturnRequestSerializer().read(protocol);
        }

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
            stringBuilder.append("\"").append("storeId").append("\":\"").append(this.storeId).append("\",");
    stringBuilder.append("\"").append("deductStockItem").append("\":").append(this.deductStockItem).append(",");
    
            stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
            stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      