/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.purchase.request;

        import java.util.Optional;
        import com.github.dapeng.org.apache.thrift.TException;
        import com.github.dapeng.org.apache.thrift.protocol.TCompactProtocol;
        import com.github.dapeng.util.TCommonTransport;

        /**
         * Autogenerated by Dapeng-Code-Generator (2.1.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

        *
        **/
        public class FFStockVo{
        
            /**
            *

 库存主体id

            **/
            public String ownerId ;
            public String getOwnerId(){ return this.ownerId; }
            public void setOwnerId(String ownerId){ this.ownerId = ownerId; }

            public String ownerId(){ return this.ownerId; }
            public FFStockVo ownerId(String ownerId){ this.ownerId = ownerId; return this; }
          
            /**
            *

 库存主体类型,1:门店(store);2:仓库(warehouse)

            **/
            public com.today.api.stock.enums.StockOwnerTypeEnum ownerType ;
            public com.today.api.stock.enums.StockOwnerTypeEnum getOwnerType(){ return this.ownerType; }
            public void setOwnerType(com.today.api.stock.enums.StockOwnerTypeEnum ownerType){ this.ownerType = ownerType; }

            public com.today.api.stock.enums.StockOwnerTypeEnum ownerType(){ return this.ownerType; }
            public FFStockVo ownerType(com.today.api.stock.enums.StockOwnerTypeEnum ownerType){ this.ownerType = ownerType; return this; }
          
            /**
            *

 库存主体名称

            **/
            public String ownerName ;
            public String getOwnerName(){ return this.ownerName; }
            public void setOwnerName(String ownerName){ this.ownerName = ownerName; }

            public String ownerName(){ return this.ownerName; }
            public FFStockVo ownerName(String ownerName){ this.ownerName = ownerName; return this; }
          
            /**
            *

商品名称

            **/
            public String skuName ;
            public String getSkuName(){ return this.skuName; }
            public void setSkuName(String skuName){ this.skuName = skuName; }

            public String skuName(){ return this.skuName; }
            public FFStockVo skuName(String skuName){ this.skuName = skuName; return this; }
          
            /**
            *

ff商品库存数

            **/
            public double ffStockWeight ;
            public double getFfStockWeight(){ return this.ffStockWeight; }
            public void setFfStockWeight(double ffStockWeight){ this.ffStockWeight = ffStockWeight; }

            public double ffStockWeight(){ return this.ffStockWeight; }
            public FFStockVo ffStockWeight(double ffStockWeight){ this.ffStockWeight = ffStockWeight; return this; }
          
            /**
            *

 FF商品计量单位

            **/
            public String useUnit ;
            public String getUseUnit(){ return this.useUnit; }
            public void setUseUnit(String useUnit){ this.useUnit = useUnit; }

            public String useUnit(){ return this.useUnit; }
            public FFStockVo useUnit(String useUnit){ this.useUnit = useUnit; return this; }
          
            /**
            *

 来源类型

            **/
            public com.today.api.stock.enums.StockJournalSourceTypeEnum sourceType ;
            public com.today.api.stock.enums.StockJournalSourceTypeEnum getSourceType(){ return this.sourceType; }
            public void setSourceType(com.today.api.stock.enums.StockJournalSourceTypeEnum sourceType){ this.sourceType = sourceType; }

            public com.today.api.stock.enums.StockJournalSourceTypeEnum sourceType(){ return this.sourceType; }
            public FFStockVo sourceType(com.today.api.stock.enums.StockJournalSourceTypeEnum sourceType){ this.sourceType = sourceType; return this; }
          
            /**
            *

 来源类型

            **/
            public long sourceTime ;
            public long getSourceTime(){ return this.sourceTime; }
            public void setSourceTime(long sourceTime){ this.sourceTime = sourceTime; }

            public long sourceTime(){ return this.sourceTime; }
            public FFStockVo sourceTime(long sourceTime){ this.sourceTime = sourceTime; return this; }
          
            /**
            *

 source_id(来源id,出入库子单Id或者是订单子单Id)

            **/
            public long orderId ;
            public long getOrderId(){ return this.orderId; }
            public void setOrderId(long orderId){ this.orderId = orderId; }

            public long orderId(){ return this.orderId; }
            public FFStockVo orderId(long orderId){ this.orderId = orderId; return this; }
          
            /**
            *

货号

            **/
            public String skuNo ;
            public String getSkuNo(){ return this.skuNo; }
            public void setSkuNo(String skuNo){ this.skuNo = skuNo; }

            public String skuNo(){ return this.skuNo; }
            public FFStockVo skuNo(String skuNo){ this.skuNo = skuNo; return this; }
          
            /**
            *

 售价(含税)

            **/
            public Optional<Double> sellingPrice = Optional.empty();
            public Optional<Double> getSellingPrice(){ return this.sellingPrice; }
            public void setSellingPrice(Optional<Double> sellingPrice){ this.sellingPrice = sellingPrice; }

            public Optional<Double> sellingPrice(){ return this.sellingPrice; }
            public FFStockVo sellingPrice(Optional<Double> sellingPrice){ this.sellingPrice = sellingPrice; return this; }
          
            /**
            *

 供应商进价(未税)

            **/
            public Optional<Double> buyingPrice = Optional.empty();
            public Optional<Double> getBuyingPrice(){ return this.buyingPrice; }
            public void setBuyingPrice(Optional<Double> buyingPrice){ this.buyingPrice = buyingPrice; }

            public Optional<Double> buyingPrice(){ return this.buyingPrice; }
            public FFStockVo buyingPrice(Optional<Double> buyingPrice){ this.buyingPrice = buyingPrice; return this; }
          
            /**
            *

 物流销价(不含税)

            **/
            public Optional<Double> logisticsPrice = Optional.empty();
            public Optional<Double> getLogisticsPrice(){ return this.logisticsPrice; }
            public void setLogisticsPrice(Optional<Double> logisticsPrice){ this.logisticsPrice = logisticsPrice; }

            public Optional<Double> logisticsPrice(){ return this.logisticsPrice; }
            public FFStockVo logisticsPrice(Optional<Double> logisticsPrice){ this.logisticsPrice = logisticsPrice; return this; }
          
            /**
            *

 物流销项税率

            **/
            public Optional<Double> logisticsOutputTax = Optional.empty();
            public Optional<Double> getLogisticsOutputTax(){ return this.logisticsOutputTax; }
            public void setLogisticsOutputTax(Optional<Double> logisticsOutputTax){ this.logisticsOutputTax = logisticsOutputTax; }

            public Optional<Double> logisticsOutputTax(){ return this.logisticsOutputTax; }
            public FFStockVo logisticsOutputTax(Optional<Double> logisticsOutputTax){ this.logisticsOutputTax = logisticsOutputTax; return this; }
          
            /**
            *

 物流销价总金额
 @datatype(name="bigdecimal")

            **/
            public Optional<java.math.BigDecimal> logisticsPriceAmount = Optional.empty();
            public Optional<java.math.BigDecimal> getLogisticsPriceAmount(){ return this.logisticsPriceAmount; }
            public void setLogisticsPriceAmount(Optional<java.math.BigDecimal> logisticsPriceAmount){ this.logisticsPriceAmount = logisticsPriceAmount; }

            public Optional<java.math.BigDecimal> logisticsPriceAmount(){ return this.logisticsPriceAmount; }
            public FFStockVo logisticsPriceAmount(Optional<java.math.BigDecimal> logisticsPriceAmount){ this.logisticsPriceAmount = logisticsPriceAmount; return this; }
          
            /**
            *

 门店售价总金额
 @datatype(name="bigdecimal")

            **/
            public Optional<java.math.BigDecimal> storeSellingPriceAmount = Optional.empty();
            public Optional<java.math.BigDecimal> getStoreSellingPriceAmount(){ return this.storeSellingPriceAmount; }
            public void setStoreSellingPriceAmount(Optional<java.math.BigDecimal> storeSellingPriceAmount){ this.storeSellingPriceAmount = storeSellingPriceAmount; }

            public Optional<java.math.BigDecimal> storeSellingPriceAmount(){ return this.storeSellingPriceAmount; }
            public FFStockVo storeSellingPriceAmount(Optional<java.math.BigDecimal> storeSellingPriceAmount){ this.storeSellingPriceAmount = storeSellingPriceAmount; return this; }
          

        public static byte[] getBytesFromBean(FFStockVo bean) throws TException {
          byte[] bytes = new byte[]{};
          TCommonTransport transport = new TCommonTransport(bytes, TCommonTransport.Type.Write);
          TCompactProtocol protocol = new TCompactProtocol(transport);

          new com.today.api.purchase.request.serializer.FFStockVoSerializer().write(bean, protocol);
          transport.flush();
          return transport.getByteBuf();
        }

        public static FFStockVo getBeanFromBytes(byte[] bytes) throws TException {
          TCommonTransport transport = new TCommonTransport(bytes, TCommonTransport.Type.Read);
          TCompactProtocol protocol = new TCompactProtocol(transport);
          return new com.today.api.purchase.request.serializer.FFStockVoSerializer().read(protocol);
        }

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
            stringBuilder.append("\"").append("ownerId").append("\":\"").append(this.ownerId).append("\",");
    stringBuilder.append("\"").append("ownerType").append("\":").append(this.ownerType).append(",");
    stringBuilder.append("\"").append("ownerName").append("\":\"").append(this.ownerName).append("\",");
    stringBuilder.append("\"").append("skuName").append("\":\"").append(this.skuName).append("\",");
    stringBuilder.append("\"").append("ffStockWeight").append("\":").append(this.ffStockWeight).append(",");
    stringBuilder.append("\"").append("useUnit").append("\":\"").append(this.useUnit).append("\",");
    stringBuilder.append("\"").append("sourceType").append("\":").append(this.sourceType).append(",");
    stringBuilder.append("\"").append("sourceTime").append("\":").append(this.sourceTime).append(",");
    stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId).append(",");
    stringBuilder.append("\"").append("skuNo").append("\":\"").append(this.skuNo).append("\",");
    stringBuilder.append("\"").append("sellingPrice").append("\":").append(this.sellingPrice.isPresent()?this.sellingPrice.get():null).append(",");
    stringBuilder.append("\"").append("buyingPrice").append("\":").append(this.buyingPrice.isPresent()?this.buyingPrice.get():null).append(",");
    stringBuilder.append("\"").append("logisticsPrice").append("\":").append(this.logisticsPrice.isPresent()?this.logisticsPrice.get():null).append(",");
    stringBuilder.append("\"").append("logisticsOutputTax").append("\":").append(this.logisticsOutputTax.isPresent()?this.logisticsOutputTax.get():null).append(",");
    stringBuilder.append("\"").append("logisticsPriceAmount").append("\":").append(this.logisticsPriceAmount.isPresent()?this.logisticsPriceAmount.get():null).append(",");
    stringBuilder.append("\"").append("storeSellingPriceAmount").append("\":").append(this.storeSellingPriceAmount.isPresent()?this.storeSellingPriceAmount.get():null).append(",");
    
            stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
            stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      