 /*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.stock.vo.serializer;
        import com.today.api.purchase.request.serializer.*;import com.today.api.common.serializer.*;import com.today.api.purchase.response.serializer.*;import com.today.api.stock.response.serializer.*;import com.today.api.stock.request.serializer.*;import com.today.api.stock.events.serializer.*;import com.today.api.stock.vo.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (2.1.1)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class TStockJournal2Serializer implements BeanSerializer<com.today.api.stock.vo.TStockJournal2>{
        
      @Override
      public com.today.api.stock.vo.TStockJournal2 read(TProtocol iprot) throws TException{

      com.today.api.stock.vo.TStockJournal2 bean = new com.today.api.stock.vo.TStockJournal2();
      TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setStockId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalSourceTypeEnum elem0 = com.today.api.stock.enums.StockJournalSourceTypeEnum.findByValue(iprot.readI32());
       bean.setSourceType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 5:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceTime(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 6:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setStockAmount(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 7:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setAfterStockNum(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 8:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalHandleTypeEnum elem0 = com.today.api.stock.enums.StockJournalHandleTypeEnum.findByValue(iprot.readI32());
       bean.setHandleType(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 9:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalIsDeletedEnum elem0 = com.today.api.stock.enums.StockJournalIsDeletedEnum.findByValue(iprot.readI32());
       bean.setIsDeleted(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 10:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setKafkaId(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 11:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setCreatedAt(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 12:
              if(schemeField.type == TType.I32){
               int elem0 = iprot.readI32();
       bean.setCreatedBy(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 13:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setUpdatedAt(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 14:
              if(schemeField.type == TType.I32){
               int elem0 = iprot.readI32();
       bean.setUpdatedBy(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 15:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setRemark(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today.api.stock.vo.TStockJournal2 bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new TStruct("TStockJournal2"));

      
            oprot.writeFieldBegin(new TField("id", TType.I64, (short) 1));
            Long elem0 = bean.getId();
            oprot.writeI64(elem0);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("stockId", TType.I64, (short) 2));
            Long elem1 = bean.getStockId();
            oprot.writeI64(elem1);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceType", TType.I32, (short) 3));
            com.today.api.stock.enums.StockJournalSourceTypeEnum elem2 = bean.getSourceType();
            oprot.writeI32(elem2.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceId", TType.I64, (short) 4));
            Long elem3 = bean.getSourceId();
            oprot.writeI64(elem3);
            
            oprot.writeFieldEnd();
          if(bean.getSourceTime().isPresent()){
              oprot.writeFieldBegin(new TField("sourceTime", TType.I64, (short) 5));
              Long elem4 = bean.getSourceTime().get();
              oprot.writeI64(elem4);
              
            }
            if(bean.getStockAmount().isPresent()){
              oprot.writeFieldBegin(new TField("stockAmount", TType.STRING, (short) 6));
              java.math.BigDecimal elem5 = bean.getStockAmount().get();
              oprot.writeString(elem5.toString());
              
            }
            if(bean.getAfterStockNum().isPresent()){
              oprot.writeFieldBegin(new TField("afterStockNum", TType.STRING, (short) 7));
              java.math.BigDecimal elem6 = bean.getAfterStockNum().get();
              oprot.writeString(elem6.toString());
              
            }
            if(bean.getHandleType().isPresent()){
              oprot.writeFieldBegin(new TField("handleType", TType.I32, (short) 8));
              com.today.api.stock.enums.StockJournalHandleTypeEnum elem7 = bean.getHandleType().get();
              oprot.writeI32(elem7.getValue());
              
            }
            if(bean.getIsDeleted().isPresent()){
              oprot.writeFieldBegin(new TField("isDeleted", TType.I32, (short) 9));
              com.today.api.stock.enums.StockJournalIsDeletedEnum elem8 = bean.getIsDeleted().get();
              oprot.writeI32(elem8.getValue());
              
            }
            if(bean.getKafkaId().isPresent()){
              oprot.writeFieldBegin(new TField("kafkaId", TType.I64, (short) 10));
              Long elem9 = bean.getKafkaId().get();
              oprot.writeI64(elem9);
              
            }
            if(bean.getCreatedAt().isPresent()){
              oprot.writeFieldBegin(new TField("createdAt", TType.I64, (short) 11));
              Long elem10 = bean.getCreatedAt().get();
              oprot.writeI64(elem10);
              
            }
            
            oprot.writeFieldBegin(new TField("createdBy", TType.I32, (short) 12));
            Integer elem11 = bean.getCreatedBy();
            oprot.writeI32(elem11);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("updatedAt", TType.I64, (short) 13));
            Long elem12 = bean.getUpdatedAt();
            oprot.writeI64(elem12);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("updatedBy", TType.I32, (short) 14));
            Integer elem13 = bean.getUpdatedBy();
            oprot.writeI32(elem13);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("remark", TType.STRING, (short) 15));
            String elem14 = bean.getRemark();
            oprot.writeString(elem14);
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today.api.stock.vo.TStockJournal2 bean) throws TException{
      
              if(bean.getSourceType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "sourceType字段不允许为空");
            
              if(bean.getRemark() == null)
              throw new SoaException(SoaCode.StructFieldNull, "remark字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today.api.stock.vo.TStockJournal2 bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      