package com.github.dapeng.soa.account.scala.enums

class AccountJournalFreezeStatus private(val id: Int, val name: String) extends com.github.dapeng.core.enums.TEnum(id,name) {}

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 

 冻结状态

      **/
      object AccountJournalFreezeStatus {

      
            val THAW = new AccountJournalFreezeStatus(1, "已解冻")
          
            val FROZENIN = new AccountJournalFreezeStatus(2, "冻结中")
          
            val PARTIALFROZENIN = new AccountJournalFreezeStatus(3, "部分冻结")
          
      val UNDEFINED = new AccountJournalFreezeStatus(-1,"UNDEFINED") // undefined enum
      

      def findByValue(v: Int): AccountJournalFreezeStatus = {
        v match {
          case 1 => THAW
            case 2 => FROZENIN
            case 3 => PARTIALFROZENIN
            
          case _ => new AccountJournalFreezeStatus(v,"#"+ v)
        }
      }

      def apply(v: Int) = findByValue(v)
      def unapply(v: AccountJournalFreezeStatus): Option[Int] = Some(v.id)

    }
    