package com.github.dapeng.soa.account.scala.enums

class CurrencyType private(val id: Int, val name: String) extends com.github.dapeng.core.enums.TEnum(id,name) {}

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 

 币种

      **/
      object CurrencyType {

      
            val CNY = new CurrencyType(0, "人民币")
          
            val USD = new CurrencyType(1, "美元")
          
      val UNDEFINED = new CurrencyType(-1,"UNDEFINED") // undefined enum
      

      def findByValue(v: Int): CurrencyType = {
        v match {
          case 0 => CNY
            case 1 => USD
            
          case _ => new CurrencyType(v,"#"+ v)
        }
      }

      def apply(v: Int) = findByValue(v)
      def unapply(v: CurrencyType): Option[Int] = Some(v.id)

    }
    