package com.github.dapeng.soa.account.scala.enums

class PrepayReceiptStatus private(val id: Int, val name: String) extends com.github.dapeng.core.enums.TEnum(id,name) {}

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 

预付款账户回款申请 状态 0 未确认:(unconfirmed),1:已确认(confirmed),2:失败(failed)

      **/
      object PrepayReceiptStatus {

      
            val UnConfirmed = new PrepayReceiptStatus(0, "未确认")
          
            val Confirmed = new PrepayReceiptStatus(1, "已确认")
          
            val Failed = new PrepayReceiptStatus(2, "失败")
          
      val UNDEFINED = new PrepayReceiptStatus(-1,"UNDEFINED") // undefined enum
      

      def findByValue(v: Int): PrepayReceiptStatus = {
        v match {
          case 0 => UnConfirmed
            case 1 => Confirmed
            case 2 => Failed
            
          case _ => new PrepayReceiptStatus(v,"#"+ v)
        }
      }

      def apply(v: Int) = findByValue(v)
      def unapply(v: PrepayReceiptStatus): Option[Int] = Some(v.id)

    }
    