package com.today.api.scheduler.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (2.1.2-SNAPSHOT)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

        * 

 任务执行状态

        **/
        public enum TaskStatusEnum implements com.github.dapeng.org.apache.thrift.TEnum{
        
            /**
            *

 执行成功

            **/
            SUCCEED(1),
          
            /**
            *

 执行失败

            **/
            FAIL(2),
          
        /*
        * 未定义的枚举类型
        */
        UNDEFINED(-1);
        private final int value;

        private TaskStatusEnum(int value){
          this.value = value;
        }

        public int getValue(){
          return this.value;
        }

        public static TaskStatusEnum findByValue(int value){
          switch(value){
            
                case 1:
                return SUCCEED;
              
                case 2:
                return FAIL;
              
            case -1:
              return UNDEFINED;
            default:
            return null;
          }
        }
      }
      