package com.isuwang.soa.order.scala.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (2.0.6)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class Order(

         /**
        *
        **/
        
        id : Int, /**
        *
        **/
        
        order_no : String, /**
        *
        **/
        
        status : Int, /**
        *
        **/
        
        amount : Double
        )
      