 /*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.purchase.request.serializer;
        import com.today.api.purchase.request.serializer.*;import com.today.api.common.serializer.*;import com.today.api.purchase.response.serializer.*;import com.today.api.stock.response.serializer.*;import com.today.api.stock.request.serializer.*;import com.today.api.stock.events.serializer.*;import com.today.api.stock.vo.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (2.1.1)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class AtomProcessStockItemSerializer implements BeanSerializer<com.today.api.purchase.request.AtomProcessStockItem>{
        
      @Override
      public com.today.api.purchase.request.AtomProcessStockItem read(TProtocol iprot) throws TException{

      com.today.api.purchase.request.AtomProcessStockItem bean = new com.today.api.purchase.request.AtomProcessStockItem();
      TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setOwnerId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockOwnerTypeEnum elem0 = com.today.api.stock.enums.StockOwnerTypeEnum.findByValue(iprot.readI32());
       bean.setOwnerType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setSkuNo(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalSourceTypeEnum2 elem0 = com.today.api.stock.enums.StockJournalSourceTypeEnum2.findByValue(iprot.readI32());
       bean.setSourceType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 5:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 6:
              if(schemeField.type == TType.I32){
               int elem0 = iprot.readI32();
       bean.setStockNum(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 7:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setKafkaId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 8:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setLogisticsPrice(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 9:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setLogisticsOutputTax(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 10:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setBuyingPrice(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 11:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setSupplierInputTax(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 12:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setSellingPirce(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 13:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setOutputTax(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 14:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setRemark(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 15:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceTime(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today.api.purchase.request.AtomProcessStockItem bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new TStruct("AtomProcessStockItem"));

      
            oprot.writeFieldBegin(new TField("ownerId", TType.STRING, (short) 1));
            String elem0 = bean.getOwnerId();
            oprot.writeString(elem0);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("ownerType", TType.I32, (short) 2));
            com.today.api.stock.enums.StockOwnerTypeEnum elem1 = bean.getOwnerType();
            oprot.writeI32(elem1.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("skuNo", TType.STRING, (short) 3));
            String elem2 = bean.getSkuNo();
            oprot.writeString(elem2);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceType", TType.I32, (short) 4));
            com.today.api.stock.enums.StockJournalSourceTypeEnum2 elem3 = bean.getSourceType();
            oprot.writeI32(elem3.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceId", TType.I64, (short) 5));
            Long elem4 = bean.getSourceId();
            oprot.writeI64(elem4);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("stockNum", TType.I32, (short) 6));
            Integer elem5 = bean.getStockNum();
            oprot.writeI32(elem5);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("kafkaId", TType.I64, (short) 7));
            Long elem6 = bean.getKafkaId();
            oprot.writeI64(elem6);
            
            oprot.writeFieldEnd();
          if(bean.getLogisticsPrice().isPresent()){
              oprot.writeFieldBegin(new TField("logisticsPrice", TType.STRING, (short) 8));
              java.math.BigDecimal elem7 = bean.getLogisticsPrice().get();
              oprot.writeString(elem7.toString());
              
            }
            if(bean.getLogisticsOutputTax().isPresent()){
              oprot.writeFieldBegin(new TField("logisticsOutputTax", TType.STRING, (short) 9));
              java.math.BigDecimal elem8 = bean.getLogisticsOutputTax().get();
              oprot.writeString(elem8.toString());
              
            }
            if(bean.getBuyingPrice().isPresent()){
              oprot.writeFieldBegin(new TField("buyingPrice", TType.STRING, (short) 10));
              java.math.BigDecimal elem9 = bean.getBuyingPrice().get();
              oprot.writeString(elem9.toString());
              
            }
            if(bean.getSupplierInputTax().isPresent()){
              oprot.writeFieldBegin(new TField("supplierInputTax", TType.STRING, (short) 11));
              java.math.BigDecimal elem10 = bean.getSupplierInputTax().get();
              oprot.writeString(elem10.toString());
              
            }
            if(bean.getSellingPirce().isPresent()){
              oprot.writeFieldBegin(new TField("sellingPirce", TType.STRING, (short) 12));
              java.math.BigDecimal elem11 = bean.getSellingPirce().get();
              oprot.writeString(elem11.toString());
              
            }
            if(bean.getOutputTax().isPresent()){
              oprot.writeFieldBegin(new TField("outputTax", TType.STRING, (short) 13));
              java.math.BigDecimal elem12 = bean.getOutputTax().get();
              oprot.writeString(elem12.toString());
              
            }
            if(bean.getRemark().isPresent()){
              oprot.writeFieldBegin(new TField("remark", TType.STRING, (short) 14));
              String elem13 = bean.getRemark().get();
              oprot.writeString(elem13);
              
            }
            
            oprot.writeFieldBegin(new TField("sourceTime", TType.I64, (short) 15));
            Long elem14 = bean.getSourceTime();
            oprot.writeI64(elem14);
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today.api.purchase.request.AtomProcessStockItem bean) throws TException{
      
              if(bean.getOwnerId() == null)
              throw new SoaException(SoaCode.StructFieldNull, "ownerId字段不允许为空");
            
              if(bean.getOwnerType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "ownerType字段不允许为空");
            
              if(bean.getSkuNo() == null)
              throw new SoaException(SoaCode.StructFieldNull, "skuNo字段不允许为空");
            
              if(bean.getSourceType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "sourceType字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today.api.purchase.request.AtomProcessStockItem bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      