 /*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.purchase.request.serializer;
        import com.today.api.purchase.request.serializer.*;import com.today.api.common.serializer.*;import com.today.api.purchase.response.serializer.*;import com.today.api.stock.response.serializer.*;import com.today.api.stock.request.serializer.*;import com.today.api.stock.events.serializer.*;import com.today.api.stock.vo.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (2.2.0-SNAPSHOT)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class CreateStockAtomActionRequestSerializer implements BeanSerializer<com.today.api.purchase.request.CreateStockAtomActionRequest>{
        
      @Override
      public com.today.api.purchase.request.CreateStockAtomActionRequest read(TProtocol iprot) throws TException{

      com.today.api.purchase.request.CreateStockAtomActionRequest bean = new com.today.api.purchase.request.CreateStockAtomActionRequest();
      TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == TType.STRUCT){
              com.today.api.stock.vo.TStock elem0 = new com.today.api.stock.vo.TStock();
        elem0=new TStockSerializer().read(iprot);
       bean.setStock(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalHandleTypeEnum elem0 = com.today.api.stock.enums.StockJournalHandleTypeEnum.findByValue(iprot.readI32());
       bean.setHandleType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalSourceTypeEnum elem0 = com.today.api.stock.enums.StockJournalSourceTypeEnum.findByValue(iprot.readI32());
       bean.setSourceType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 5:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceTime(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today.api.purchase.request.CreateStockAtomActionRequest bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new TStruct("CreateStockAtomActionRequest"));

      
            oprot.writeFieldBegin(new TField("stock", TType.STRUCT, (short) 1));
            com.today.api.stock.vo.TStock elem0 = bean.getStock();
             new TStockSerializer().write(elem0, oprot);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("handleType", TType.I32, (short) 2));
            com.today.api.stock.enums.StockJournalHandleTypeEnum elem1 = bean.getHandleType();
            oprot.writeI32(elem1.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceType", TType.I32, (short) 3));
            com.today.api.stock.enums.StockJournalSourceTypeEnum elem2 = bean.getSourceType();
            oprot.writeI32(elem2.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceId", TType.I64, (short) 4));
            Long elem3 = bean.getSourceId();
            oprot.writeI64(elem3);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceTime", TType.I64, (short) 5));
            Long elem4 = bean.getSourceTime();
            oprot.writeI64(elem4);
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today.api.purchase.request.CreateStockAtomActionRequest bean) throws TException{
      
              if(bean.getStock() == null)
              throw new SoaException(SoaCode.StructFieldNull, "stock字段不允许为空");
            
                if(bean.getStock() != null)
                new TStockSerializer().validate(bean.getStock());
              
              if(bean.getHandleType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "handleType字段不允许为空");
            
              if(bean.getSourceType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "sourceType字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today.api.purchase.request.CreateStockAtomActionRequest bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      