 /*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.today.api.purchase.request.serializer;
        import com.today.api.purchase.request.serializer.*;import com.today.api.common.serializer.*;import com.today.api.purchase.response.serializer.*;import com.today.api.stock.response.serializer.*;import com.today.api.stock.request.serializer.*;import com.today.api.stock.events.serializer.*;import com.today.api.stock.vo.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (2.2.0)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class UpdateInventoryVoSerializer implements BeanSerializer<com.today.api.purchase.request.UpdateInventoryVo>{
        
      @Override
      public com.today.api.purchase.request.UpdateInventoryVo read(TProtocol iprot) throws TException{

      com.today.api.purchase.request.UpdateInventoryVo bean = new com.today.api.purchase.request.UpdateInventoryVo();
      TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setStoreId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == TType.STRING){
              String elem0 = iprot.readString();
       bean.setSkuNo(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == TType.STRING){
              java.math.BigDecimal elem0 = new java.math.BigDecimal(iprot.readString());
       bean.setStockAmount(Optional.of(elem0));
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 5:
              if(schemeField.type == TType.I64){
              long elem0 = iprot.readI64();
       bean.setSourceId(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 6:
              if(schemeField.type == TType.I32){
              com.today.api.stock.enums.StockJournalSourceTypeEnum elem0 = com.today.api.stock.enums.StockJournalSourceTypeEnum.findByValue(iprot.readI32());
       bean.setSourceType(elem0);
            }else{
              TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today.api.purchase.request.UpdateInventoryVo bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new TStruct("UpdateInventoryVo"));

      
            oprot.writeFieldBegin(new TField("storeId", TType.STRING, (short) 1));
            String elem0 = bean.getStoreId();
            oprot.writeString(elem0);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("skuNo", TType.STRING, (short) 3));
            String elem1 = bean.getSkuNo();
            oprot.writeString(elem1);
            
            oprot.writeFieldEnd();
          if(bean.getStockAmount().isPresent()){
              oprot.writeFieldBegin(new TField("stockAmount", TType.STRING, (short) 4));
              java.math.BigDecimal elem2 = bean.getStockAmount().get();
              oprot.writeString(elem2.toString());
              
            }
            
            oprot.writeFieldBegin(new TField("sourceId", TType.I64, (short) 5));
            Long elem3 = bean.getSourceId();
            oprot.writeI64(elem3);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new TField("sourceType", TType.I32, (short) 6));
            com.today.api.stock.enums.StockJournalSourceTypeEnum elem4 = bean.getSourceType();
            oprot.writeI32(elem4.getValue());
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today.api.purchase.request.UpdateInventoryVo bean) throws TException{
      
              if(bean.getStoreId() == null)
              throw new SoaException(SoaCode.StructFieldNull, "storeId字段不允许为空");
            
              if(bean.getSkuNo() == null)
              throw new SoaException(SoaCode.StructFieldNull, "skuNo字段不允许为空");
            
              if(bean.getSourceType() == null)
              throw new SoaException(SoaCode.StructFieldNull, "sourceType字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today.api.purchase.request.UpdateInventoryVo bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      