
        package com.isuwang.soa.user.service;

        import com.github.dapeng.core.Processor;
        import com.github.dapeng.core.Service;
        import com.github.dapeng.core.SoaGlobalTransactional;

        import java.util.concurrent.Future;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name="com.isuwang.soa.user.service.UserService",version = "1.0.0")
        @Processor(className = "com.isuwang.soa.user.UserServiceAsyncCodec$Processor")
        public interface UserServiceAsync  extends com.github.dapeng.core.definition.AsyncService {
        
            /**
            * 
            **/
            
            
              Future<Void> createUser( com.isuwang.soa.user.domain.User user) throws com.github.dapeng.core.SoaException;
            
          
            /**
            * 
            **/
            
            
              Future<com.isuwang.soa.user.domain.User> getUserById( Integer userId) throws com.github.dapeng.core.SoaException;
            
          
      }
      